trigger:
  - main
  - master

variables:
  # Container registry service connection establecida durante la configuración de la pipeline
  dockerRegistryServiceConnection: 'acr-connecti'
  containerRegistry: 'acrmicroappdgwb6c.azurecr.io'
  # Versión de las imágenes
  tag: '$(Build.BuildId)'
  # Variables para el despliegue
  resourceGroup: 'rg-microservice-app'

stages:
- stage: Build
  displayName: 'Build and Push Images'
  jobs:
  - job: BuildAndPushImages
    displayName: 'Build and Push All Microservices'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push auth-api'
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: 'auth-api'
        dockerfile: '$(System.DefaultWorkingDirectory)/auth-api/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/auth-api'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Build and Push frontend '
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: 'frontend'
        dockerfile: '$(System.DefaultWorkingDirectory)/frontend/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/frontend'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Build and Push log-message-processor'
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: 'log-message-processor'
        dockerfile: '$(System.DefaultWorkingDirectory)/log-message-processor/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/log-message-processor'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Build and Push todos-api'
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: 'todos-api'
        dockerfile: '$(System.DefaultWorkingDirectory)/todos-api/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/todos-api'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Build and Push users-api'
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: 'users-api'
        dockerfile: '$(System.DefaultWorkingDirectory)/users-api/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/users-api'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: 'Update Container Apps'
  dependsOn: Build
  jobs:
  - job: UpdateContainerApps
    displayName: 'Update Container Apps with Latest Images'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Update Container Apps'
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Actualizar auth-api
          az containerapp update -n auth-api -g $(resourceGroup) \
            --image $(containerRegistry)/auth-api:latest

          # Actualizar users-api
          az containerapp update -n users-api -g $(resourceGroup) \
            --image $(containerRegistry)/users-api:latest
            
          # Actualizar todos-api
          az containerapp update -n todos-api -g $(resourceGroup) \
            --image $(containerRegistry)/todos-api:latest
            
          # Actualizar log-processor
          az containerapp update -n log-processor -g $(resourceGroup) \
            --image $(containerRegistry)/log-message-processor:latest
            
          # Actualizar frontend
          az containerapp update -n frontend -g $(resourceGroup) \
            --image $(containerRegistry)/frontend:latest
